services:
  - type: web
    name: halo-pet-care
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20.18.0

